server:
  port: 8011

spring:
  h2:
    console:
      enabled: true
      path: /test
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
  output:
    ansi:
      enabled: always